import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  education: [{type: "autogenerated", dirName: "education"}],
  roadmap: [{type: "autogenerated", dirName: "roadmap"}],
  preparation: [{type: "autogenerated", dirName: "preparation"}],
  toolset: [{type: "link", label: "Toolset", href: "/toolset"}],
};

export default sidebars;
